# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Combo.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(400, 300)
        self.cmp_programlama_dili = QtWidgets.QComboBox(Form)
        self.cmp_programlama_dili.setGeometry(QtCore.QRect(30, 90, 141, 22))
        self.cmp_programlama_dili.setObjectName("cmp_programlama_dili")
        self.cmp_programlama_dili.addItem("")
        self.cmp_programlama_dili.addItem("")
        self.edt_sonuc = QtWidgets.QLineEdit(Form)
        self.edt_sonuc.setGeometry(QtCore.QRect(220, 90, 131, 20))
        self.edt_sonuc.setText("")
        self.edt_sonuc.setObjectName("edt_sonuc")
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(30, 50, 171, 16))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(220, 50, 171, 20))
        font = QtGui.QFont()
        font.setFamily("MS Sans Serif")
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        
        self.cmp_programlama_dili.addItems({"Java","C#"})
        
        self.cmp_programlama_dili.currentIndexChanged.connect(self.sonuc_kutusunu_doldur)
        
        
        

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        
      

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Combo Box Kullanım"))
        self.cmp_programlama_dili.setItemText(0, _translate("Form", "Python"))
        self.cmp_programlama_dili.setItemText(1, _translate("Form", "C++"))
        self.label.setText(_translate("Form", "Programlama Dilleri Seçiniz"))
        self.label_2.setText(_translate("Form", "Seçtiğimiz programlama dili:"))
        
    def sonuc_kutusunu_doldur(self):
        secilen=self.cmp_programlama_dili.currentText()
        self.edt_sonuc.setText(secilen)
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
