# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1..ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.buttonBox = QtWidgets.QDialogButtonBox(Dialog)
        self.buttonBox.setGeometry(QtCore.QRect(30, 240, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.btn_buyukharf_yap = QtWidgets.QPushButton(Dialog)
        self.btn_buyukharf_yap.setGeometry(QtCore.QRect(210, 50, 131, 23))
        self.btn_buyukharf_yap.setObjectName("btn_buyukharf_yap")
        self.btn_karaktersay_bul = QtWidgets.QPushButton(Dialog)
        self.btn_karaktersay_bul.setGeometry(QtCore.QRect(210, 110, 121, 23))
        self.btn_karaktersay_bul.setObjectName("btn_karaktersay_bul")
        self.edt_mesaj = QtWidgets.QLineEdit(Dialog)
        self.edt_mesaj.setGeometry(QtCore.QRect(70, 50, 113, 20))
        self.edt_mesaj.setObjectName("edt_mesaj")
        self.edt_sonuc = QtWidgets.QLineEdit(Dialog)
        self.edt_sonuc.setGeometry(QtCore.QRect(70, 110, 113, 20))
        self.edt_sonuc.setObjectName("edt_sonuc")
        
        self.btn_buyukharf_yap.clicked.connect(self.btn_buyukharf_yap_clicked)
        self.btn_karaktersay_bul.clicked.connect(self.btn_karaktersay_bul_clicked)
        
        

        self.retranslateUi(Dialog)
        self.buttonBox.accepted.connect(Dialog.accept) # type: ignore
        self.buttonBox.rejected.connect(Dialog.reject) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btn_buyukharf_yap.setText(_translate("Dialog", "Büyük harfe dönüştür"))
        self.btn_karaktersay_bul.setText(_translate("Dialog", "Karakter sayısını bul"))
        
    def btn_buyukharf_yap_clicked(self):
        msj=self.edt_mesaj.text()
        yeni_mesaj=msj.upper()
        self.edt_sonuc.setText(yeni_mesaj)
        
    def btn_karaktersay_bul_clicked(self):
        msj=self.edt_mesaj.text()
        yeni_mesaj=str(len(msj))
        self.edt_sonuc.setText(yeni_mesaj)
        
        
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
